services:
  - type: web
    name: StudyHub-backend
    env: java
    plan: free
    buildCommand: "./mvnw package -DskipTests"
    startCommand: "java -jar target/studyhub-0.0.1-SNAPSHOT.jar"
    rootDir: back
    buildEnvVars:
      JAVA_VERSION: 21
